version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: assesspro-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - assesspro-net

  app:
    build: .
    container_name: assesspro-app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://postgres:5432/dev_postgres?currentSchema=assess_pro_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - assesspro-net

volumes:
  postgres_data:

networks:
  assesspro-net: